baseURL = "https://forwardingplane.net/"
languageCode = "en-us"
title = "ForwardingPlane.net"
copyright = "Copyright (c) 2019, all rights reserved."
canonifyurls = true
enableRobotsTXT = true
theme = "hugo-future-imperfect"
#disqusShortname = "forwwardingplane"
pygmentsCodeFences = "true"
#theme_colors = "default-dark" # uses color css file under static/css/default-dark.css

[author]
  name = "Nick Buraglio"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
#pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech, Nick Buraglio, SDN, Security, OpenFlow, Service Provider"
  description = "A wealth of run on sentences, misspelled words, and grammatical errors related to Routing, Switching, Security, Strategyâ€¦.The Lunatic fringe."

#[params.postAmount]
#[params]
[social]
  github = "buraglio"
  twitter = "forwardingplane"
  linkedin = "buraglio"
  email = "my lastname at forwardingplane dot net"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"

#  [[menu.main]]
#    identifier = "resume"
#    name = "resume"
#    url = "/resume"

#  [[menu.main]]
#    identifier = "configuration-archive"
#    name = "configuration-archive"
#    url = "/configuration-archive"

[permalinks]
  posts = "/:year/:month/:title/"
