[context.production.environment]
  HUGO_VERSION = "v0.122.2"
#[[redirects]]
#  from = "/"
#  to = "/public"
[[redirects]]
from = "/feed/"
to = "/post/index.xml"
status = 301
force = true
# query = {path = ":path"}
# conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
