[context.production.environment]
  HUGO_VERSION = "0.122.0"
[[redirects]]
from = "/feed/"
to = "/post/index.xml"
status = 301
force = true
# query = {path = ":path"}
# conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
