[context.production.environment]
HUGO_VERSION = "0.92.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
# HUGO_THEME = "repo"

[[redirects]]
from = "/feed/"
to = "/post/index.xml"
status = 301
force = true
# query = {path = ":path"}
# conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
